Fix: Firefox console errors `TypeError: this.preferredCodec.split is not a function` (#310) (#313)
* Fix select codec on Firefox

* Restore indentation in cirrus

(cherry picked from commit 503b565bc5aa5b80594cef20aae2530dc60cb7df)

Co-authored-by: William Belcher <william.belcher@xa.epicgames.com>